# Generated by Django 2.2.6 on 2019-10-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moi_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
