# Generated by Django 2.2.6 on 2019-10-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moi_api', '0002_remove_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
