# Generated by Django 2.2.6 on 2019-10-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moi_api', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorite',
        ),
    ]
